// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using PropertyPageBase;
using PropertyPageBaseTest.Mocks;
namespace PropertyPageBaseTest
{
    [TestClass()]
    public class SimplePageViewTest
    {
        

    }


}
